import { paymentMethodsSummary, paymentRulesScope, paymentDetailsNotice, returnsPolicySummary, returnsDetailsNotice } from "./payment-rules.mjs";

export const guideTopics = [
  {id:'restrictions',label:'Prohibited items',words:['prohibited','restricted items','restrictions','banned','not allowed'],text:'We do not accept illegal, stolen or counterfeit goods, weapons, drugs, regulated substances, hazardous goods, personal data, exploitative content, live animals/protected wildlife, or fraudulent financial offers. Read the full policy before selling or requesting USA shopping. To report a listing, send its link to the human support team.',links:[['Read prohibited-items policy','/prohibited-items']]},
  {id:'start',label:'I’m new here',words:['new user','getting started','start','how to use','beginner'],text:'Welcome! Browse items from the homepage. To bid, create an account, confirm your email, then submit your government ID for administrator approval. You can browse and contact sellers about buying. Selling and listing posts are currently for administrators only; selling for members is coming soon. For USA shopping, you can sign in and request a quote before deciding on a purchase.',links:[['Create an account / sign in','/login'],['Browse items','/#browse']]},
  {id:'account',label:'Create an account',words:['register','registration','sign up','signup','account','login','log in','password','email confirmation'],text:'Open Login and choose Sign Up. Enter your email and password, then check your email for the confirmation link. Sign in and open Account Verification to submit your ID. If you forgot your password, enter your email on Login and choose Forgot password. Never send your password in chat.',links:[['Open Login / Sign Up','/login'],['Verify my account','/verify']]},
  {id:'verify',label:'ID & approval',words:['verify','verification','government id','valid id','approval','approved','rejected','pending','identity'],text:'Sign in and open Account Verification. Enter your full name and ID type, then upload a clear JPEG, PNG or WebP photo up to 5 MB. Your submission stays pending until an administrator reviews it. If rejected, check the review note and resubmit. I cannot inspect your ID or approve your account.',links:[['Check verification status','/verify']]},
  {id:'sell',label:'Sell or edit an item',words:['sell','seller','listing','list an item','edit','photo','upload','picture'],text:'Selling and listing posts are currently available only to administrators. Selling for members is coming soon. You can browse items, contact sellers about buying and bid on live auctions after ID approval. Administrators can create and edit their own listings without the seller ID-approval gate. Add item details, shipping carrier and fee, and choose fixed price or bidding. Up to eight photos are supported, including automatic HEIC/HEIF conversion. Existing ownership, auction-term and prohibited-items rules still apply.',links:[['Selling information','/sell'],['Browse items','/search'],['My account','/account']]},
  {id:'bid',label:'Place a bid',words:['bid','bidding','auction','current bid'],text:`Sign in with an approved account and open an active auction’s product page. Enter at least the next minimum bid shown, then choose Place bid. You cannot bid on your own listing or an auction that has not started or has ended. Shipping is separate from the winning bid. ${paymentMethodsSummary} ${returnsPolicySummary} Check the success message and updated price before submitting again.`,links:[['Browse items and auctions','/#auctions'],['Check ID approval','/verify'],['Payment and return rules','/payment-rules']]},
  {id:'usa',label:'Buy from the USA',words:['usa','us store','america','import','wishlist','quote','bring','philippines'],text:'Open Buy from USA, sign in, and send the item name, full HTTPS store link, size/color/model, quantity, delivery city/province and contact details. The team reviews availability and discusses item cost, service fee, shipping and applicable import charges. This is a quote request, not an order or payment. Delivery timing is confirmed individually, and ID approval is required before a purchase proceeds.',links:[['Request USA shopping help','/usa-shopping']]},
  {id:'shipping',label:'Shipping & fees',words:['shipping','courier','lbc','j&t','delivery fee','shipping fee','free shipping'],text:'Check the listing’s Shipping section for the seller’s courier and fee. LBC, J&T Express and other supported couriers are available. Shipping is charged separately from the item price or winning bid; a fee of ₱0 means free shipping. If the listing says shipping details are not provided, ask support for help before agreeing to a purchase.',links:[['Browse listings','/#browse']]},
  {id:'buy',label:'Buying & payments',words:['buy','buyer','purchase','payment','checkout','pay','order','gcash','bank deposit','bank','cash on delivery','cod','winning bid'],text:`${paymentMethodsSummary} ${paymentRulesScope} ${paymentDetailsNotice} ${returnsPolicySummary} Review the description, condition, location and shipping fee. Payments are arranged directly with the seller; this website guide cannot collect or confirm payments. Contact the human support team for help.`,links:[['Read payment and return rules','/payment-rules'],['Browse listings','/#browse']]},
  {id:'returns',label:'Returns',words:['return','returns','refund','refunds','change of mind','defective','damaged','incorrect item'],text:`${returnsPolicySummary} ${paymentRulesScope} Review the photos, description and condition before buying or bidding. ${returnsDetailsNotice} The guide cannot process a return or refund; contact the human support team for help.`,links:[['Read payment and return rules','/payment-rules']]},
];
export function answerGuide(question) {
  const text=String(question).toLowerCase().trim();
  if(!text) return null;
  const match=guideTopics.map(topic=>({topic,score:topic.words.reduce((score,word)=>score+(new RegExp(`(^|[^a-z])${word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}([^a-z]|$)`,'i').test(text)?word.length:0),0)})).sort((a,b)=>b.score-a.score)[0];
  return match?.score ? match.topic : {id:'unknown',text:'I’m an automated website guide, so I can help with signup, ID verification, listings, bidding, shipping and USA shopping. I can’t check your personal account, change a bid or resolve a dispute. Choose a topic below or message our support team for help.',links:[]};
}
