"use client";
import {useEffect,useState} from "react";
import Header from "@/components/Header";
import {supabase} from "@/lib/supabase";
import {withDeadline} from "@/lib/verification-actions";
export default function AdminSupport(){
 const [tickets,setTickets]=useState([]),[selected,setSelected]=useState(null),[messages,setMessages]=useState([]),[body,setBody]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('Checking administrator access...'),[allowed,setAllowed]=useState(false);
 async function load(){try{const check=await withDeadline(supabase.rpc('is_marketplace_admin'));if(check.error||!check.data){setAllowed(false);setNotice('Administrator access required.');return}setAllowed(true);const r=await withDeadline(supabase.from('support_tickets').select('*').order('created_at',{ascending:false}).limit(100));if(r.error)throw r.error;setTickets(r.data||[]);setNotice('')}catch{setNotice('Could not load support. Check that the support migration is installed.')}}
 useEffect(()=>{load()},[]);
 async function view(t){setBusy(true);setBody('');try{const r=await withDeadline(supabase.from('support_messages').select('*').eq('ticket_id',t.id).order('id',{ascending:false}).limit(100));if(r.error)throw r.error;setSelected(t);setMessages((r.data||[]).reverse());setNotice('')}catch{setNotice('Could not load this conversation.')}finally{setBusy(false)}}
 async function send(e){e.preventDefault();if(busy)return;setBusy(true);try{const r=await withDeadline(supabase.rpc('send_support_message',{p_ticket_id:selected.id,p_body:body.trim()}));if(r.error)throw r.error;await view(selected);setNotice('Reply sent. It will appear in the customer’s support popup.')}catch(err){setNotice(err.message||'Reply failed. Refresh before retrying.')}finally{setBusy(false)}}
 async function close(){setBusy(true);try{const r=await withDeadline(supabase.from('support_tickets').update({status:'closed'}).eq('id',selected.id).select('id').single());if(r.error)throw r.error;setSelected({...selected,status:'closed'});await load();setNotice('Conversation closed.')}catch{setNotice('Could not close conversation.')}finally{setBusy(false)}}
 return <><Header/><main className="page"><div className="container narrow"><h1>Support inbox</h1>{notice&&<p role="status">{notice}</p>}<button className="view" disabled={busy} onClick={load}>Refresh inbox</button>{allowed&&tickets.length===0&&<p>No conversations yet.</p>}
 {selected&&<section className="listing-form" style={{padding:20,border:'2px solid #2454d6'}}><h2>{selected.contact_name}</h2><p>{selected.contact_email} · {selected.status}</p><button className="view" disabled={busy} onClick={()=>view(selected)}>Refresh conversation</button>{messages.map(m=><div key={m.id} className={`support-message support-${m.sender_role}`}><strong>{m.sender_role==='support'?'Support':'Customer'}</strong><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString()}</small></div>)}{selected.status==='open'&&<><form className="listing-form" onSubmit={send}><label>Your reply<textarea required maxLength={2000} rows={4} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="sell" disabled={busy}>Send reply</button></form><button className="view" disabled={busy} onClick={close}>Close conversation</button></>}</section>}
 {allowed&&tickets.map(t=><button key={t.id} className="view" disabled={busy} onClick={()=>view(t)}>{t.contact_name} · {t.status} · {new Date(t.created_at).toLocaleString()}</button>)}</div></main></>;
}
